# Generated by Django 6.0.2 on 2026-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
