# Generated by Django 6.0.2 on 2026-02-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_testresult_passed_testresult_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
